const ActionTypes={
    ASYNC_START:"ASYNC_START",
    ASYNC_END:"ASYNC_END",
    ANIMALS_TYPE:{
        InsertAnimal:  "InsertAnimal",
        FETCH_ANIMALS: "FETCH_ANIMALS",
        FETCH_ANIMAL: "FETCH_ANIMAL",
        FETCH_ANIMALS_SUCCESS: "FETCH_ANIMALS_SUCCESS",
        FETCH_ANIMALS_PENDING: "FETCH_ANIMALS_PENDING",

    },
    RIVIA_TYPE:{
        INSERT_RIVIA: "INSERT_RIVIA",
        FETCH_RIVIA: "FETCH_RIVIA",
        FETCH_ANIMALS_SUCCESS: "FETCH_RIVIA_SUCCESS"
    }
}

export default ActionTypes